### ISSUE TITLE
Website lädt nicht

### ISSUE THREAD

**Issue by vv01f** [chaostreff-alzey/chaostreff-alzey.github.io#10]
Die Website wirft Fehler… das sollte mal mit allen Betablockern auf aktiv getestet werden.

**Comment by vv01f** [comment]
Da gibt es wohl Policies zu Frames und die Seite auf github.io wurde so eingebunden. Das ist für einen Besucher auf der eigentlichen Domain eher unschön.

Reproduzierbar u.a. mit uMatrix 1.4.0

**Comment by TheLie0** [comment]
Läuft jetzt über header-weiterleitung.
