### ISSUE TITLE
SSL/TLS einschalten

### ISSUE THREAD

**Issue by vollkorn1982** [chaostreff-alzey/chaostreff-alzey.github.io#13]
Moin,

abgesehen davon, dass es keinen Kontakt auf eurer [Webseite](https://chaostreff-alzey.de/) gibt, fehlt dort SSL/TLS. Als einer der Admins von ccc.de möchte ich es echt hart vermeiden HTTP-Links auf https://www.ccc.de/de/club/chaostreffs zu packen.

Also, macht mal das SSL/TLS an, denn derzeit gibt's nur ne Fehlermeldung, wenn Besucher von ccc.de euren auf den Link eures Chaostreffs klicken. Ich empfehle Let's Encrypt.

Gruß
vollkorn

**Comment by TheLie0** [comment]
Ist beides in Arbeit und hoffentlich bis ende der Woche fertig.

**Comment by TheLie0** [comment]
Der Internet-Provider hatte eine leicht andere Vorstellung von "Ende der Woche", aber jetzt läuft alles.
